### ISSUE TITLE
Suspend and resume

### ISSUE THREAD

**Issue by rubdos** [dalek-cryptography/merlin#35]
In [your excellent Medium article](https://medium.com/@hdevalence/merlin-flexible-composable-transcripts-for-zero-knowledge-proofs-28d9fda22d9a) you speak about "Interactive composition of noninteractive proofs".

I was thinking about a scenario where Client and Server are communicating with a significant delay (days to weeks), in which case in might make sense to "suspend" the current protocol and application to storage, effectively serializing the internal state in between communication.

Does this make sense from the security standpoint? I would assume it comes with some disadvantages (like reuse of the suspended state?)

If it does make sense to you, would you accept a pull request for (de)serializing the state? I assume that STROBE also needs modification to support this.

**Comment by burdges** [comment]
Assuming these breakpoints are rather specific then you'd usually serialize by extracting 16 or 32 bytes with `challenge_bytes` and latter deserialize by adding these bytes to a new transcript using `commit_bytes`, with appropriately specific contexts.

**Comment by rubdos** [comment]
Fair point. Thanks! What I'm still wondering about then, is whether I can commit values in a first phase, and use them in a proof after a suspend-resume. I guess this is a problem for [`bulletproofs`](https://github.com/dalek-cryptography/bulletproofs/), then.
