### ISSUE TITLE
Rename transcript functions

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/merlin#38]
In retrospect, the transcript functions could have been better-named.  For 1.1, I'm planning to rename them and leave the old ones in place as `#[deprecated]` functions.

Renaming:

* `commit_bytes` -> `append_message` (avoids concept collision between the transcript layer and some protocol's commitments)
* `commit_witness_bytes` -> `rekey_with_witness_bytes` (makes rekeying explicit)

**Comment by oleganza** [comment]
I've noticed this issue only today. Sounds good 👍

**Comment by hdevalence** [comment]
Closed by #39
