### ISSUE TITLE
STROBE_R = 166

### ISSUE THREAD

**Issue by rubdos** [dalek-cryptography/merlin#46]
I was confused when I encountered

```rust
/// Strobe R value; security level 128 is hardcoded
const STROBE_R: u8 = 166;
```

R=166 means that 166 bytes=1328 bits can be extracted (the rate) from the Keccak state. That leaves 34 bytes=272 bits of sponge capacity. These numbers seem weird to me; especially since intuition would tell me that 128 bits security would mean 32 bytes of capacity and thus a rate of 168 bytes (or even c=16 bytes and r=184 bytes).

Am I forgetting something? I'm not a Keccak expert!

**Comment by hdevalence** [comment]
Hey, I think your intuition is correct -- IIRC the Keccak rate is 168, but STROBE uses two bytes to encode operation flags, and instead of doing R-2 all the time I encoded R as 166.

**Comment by rubdos** [comment]
Would you like a patch with that explanation as comment?

**Comment by hdevalence** [comment]
Thanks, but I would want to double-check the explanation before adding it as a comment (it's kind of half-baked, just based on my recollection), so I can do that and add it in later :)
