### ISSUE TITLE
Update rand_core to 0.5

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/merlin#53]
This would make it compatible with curve25519-dalek-2.0.0-alpha.1.

**Comment by isislovecruft** [comment]
Unless I'm mistaken, this would be a breaking change, requiring a merlin 2.0.0-alpha.1.

**Comment by isislovecruft** [comment]
Oh, also we should update rand to 0.7 while we're at it.

**Comment by hdevalence** [comment]
Hi, I was waiting to do this until a compatible `curve25519-dalek` version was available. It's on my agenda for this week.
