### ISSUE TITLE
the package name seems to need to change?

### ISSUE THREAD

**Issue by gilescope** [dalek-cryptography/merlin#63]
version 3 of the merlin crate is merlin-ng effectively. I think this crate should be called merlin-og? or we could ask him nicely to yank and republish under merlin-ng... this is the joys of gits decentralisation meeting crates.io's centralisation...

**Comment by gilescope** [comment]
or alternatively this could be archived? depends which way you want to go...

**Comment by hdevalence** [comment]
There's only ever been one merlin crate; the location of its upstream repo changed when @isislovecruft seized control of this GitHub org.

I asked them last December to return the repos for the projects that weren't theirs in the first place, and they didn't respond to email, so I forked the repos.

**Comment by gilescope** [comment]
I understand where you’re coming from but there’s a dependency from this
crate on curve25519-dalek which is now pointing to the ng one.

From a security perspective it’s preferable that people are using all your
crates or use all of the preforked crates. We don’t really want both
compiled into a dependency tree ideally to reduced binary sizes and attack
vectors. It a free world and people can choose to go either way. But
ideally we don’t want curve25519-dalek and curve25519-dalek-ng in the same
binary if we can help it. Because of this I think it would be sensible that
there are two versions of the merlin crate.

I also want to take a moment just to say thank you to all of you for
working on pushing cryptography forward and maintaining these crates -
thank you *all* for keeping us safe. It is very much appreciated!

**Comment by hdevalence** [comment]
The dependency on `curve25519-dalek-ng` is a dev-dependency that's only used for the internal unit tests, it doesn't affect any downstream users of the library or their dep trees.

**Comment by gilescope** [comment]
Good point.
